ignore:
    - "misc/specs"
    - "misc/tools"
    - "samples"

    #TODO remove all below with 1.0.0
    - "misc/verb/**/atrium/verbs/**/*"
    - "misc/deprecated/atrium-assertions"
    - "misc/deprecated/atrium-spec"
    - "misc/deprecated/domain/api/**/assertions/**/*"
    - "misc/deprecated/domain/atrium-domain-api-deprecated"
    - "misc/deprecated/domain/builders/**/AssertImpl.kt"
    - "misc/deprecated/domain/builders/**/ExpectImpl.kt"
    - "misc/deprecated/domain/builders/**/ExpectImplExtensions.kt"
    - "misc/deprecated/domain/builders/**/creating/*AssertionsBuilder.kt"
    - "misc/deprecated/domain/builders/**/creating/*AssertionsBuilders.kt"
    - "misc/deprecated/domain/builders/**/utils/nullable.kt"
    - "misc/deprecated/domain/builders/**/utils/subAssert.kt"
    - "**/IAtriumFactory.kt"
    - "**/AtriumFactory.kt"

coverage:
    range: 70..95
    status:
        project:
            default:
                target: 85%
        patch:
            default:
                target: 85%
