ignore:
  - "misc/specs"
  - "misc/tools"
  - "samples"

coverage:
  range: 70..95
  status:
    project:
      default:
        target: 84%
    patch:
      default:
        target: 85%

codecov:
  branch: main
  notify:
    after_n_builds: 5
comment:
  after_n_builds: 5
