package ch.tutteli.atrium.core.polyfills

interface InterfaceWithOneImplementation
class SingleService : InterfaceWithOneImplementation

interface InterfaceWithTwoImplementation
class Service1 : InterfaceWithTwoImplementation
class Service2 : InterfaceWithTwoImplementation
