//
//    __                          __
//   / /____ ___ ____  ___  ___ _/ /       This file is provided to you by https://github.com/tegonal/github-commons
//  / __/ -_) _ `/ _ \/ _ \/ _ `/ /        Copyright 2022 Tegonal Genossenschaft <info@tegonal.com>
//  \__/\__/\_, /\___/_//_/\_,_/_/         It is licensed under Apache License 2.0
//         /___/                           Please report bugs and contribute back your improvements
//
//                                         Version: v6.0.0
//##################################
// adapted version of https://github.com/vlsi/github-actions-random-matrix/blob/main/examples/matrix.mjs
// licensed under Apache License 2.0
//##################################
import {MatrixBuilder, setGitHubOutput} from "./vlsi_matrix_builder.mjs";

const javaDistributionAxis = {
	name: 'java_distribution',
	values: [
		'corretto',
		'dragonwell',

		// we ran into github API rate limits with those two from time to time, disable them if it starts to be too annoying
		'graalvm',
		//'jetbrains',

		'liberica',
		'microsoft',
		'sapmachine',
		'semeru',
		'temurin',
		'zulu',
	]
};

const javaVersionAxis = {
	name: 'java_version',
	title: x => 'Java ' + x,
	values: ['11', '17', '21', '25']
}

const osAxis = {
	name: 'os',
	title: x => x.replace('-latest', ''),
	values: [
		'ubuntu-latest',
		'windows-latest',
		'macos-latest'
	]
}

/**
 * @param {MatrixBuilder} matrix
 * @param {Object} [axes]
 * @param {*} [axes.versionAxis=javaVersionAxis]
 * @param {*} [axes.distributionAxis=javaDistributionAxis]
 * @param {*} [axes.operatingSystemAxis=osAxis]
 */
function configureJavaDefaults(
	matrix,
	{
		versionAxis = javaVersionAxis,
		distributionAxis = javaDistributionAxis,
		operatingSystemAxis = osAxis,
	} = {}
) {
	matrix.addAxis(versionAxis);
	matrix.addAxis(distributionAxis);
	matrix.addAxis(operatingSystemAxis);

	// graalvm requires at least jdk 17 but for jdk 17 only jdk 17.0.12 is supported (but rewriting 17 to 17.0.12 has
	// other implications). Thus, to keep it simple, we don't support jdk 11 and 17 for graalvm
	matrix.exclude({java_distribution: 'graalvm', java_version: '11'});
	matrix.exclude({java_distribution: 'graalvm', java_version: '17'});

	// dragonwell doesn't support macOS (arm64)
	matrix.exclude({java_distribution: 'dragonwell', os: 'macos-latest'});

	// This specifies the order of axes in CI job name (individual titles would be joined with a comma)
	matrix.setNamePattern(['java_version', 'java_distribution', 'os']);
}

/**
 * @param {MatrixBuilder} matrix
 * @param {Object} [axes]
 * @param {*} [axes.versionAxis=javaVersionAxis]
 * @param {*} [axes.distributionAxis=javaDistributionAxis]
 * @param {*} [axes.operatingSystemAxis=osAxis]
 */
function configureKotlinDefaults(matrix, axes = {}) {
	configureJavaDefaults(matrix, axes);
}

/**
 * @param {MatrixBuilder} matrix
 * @param {Object} [axes]
 * @param {*} [axes.versionAxis=javaVersionAxis]
 * @param {*} [axes.distributionAxis=javaDistributionAxis]
 * @param {*} [axes.operatingSystemAxis=osAxis]
 */
function configureScalaDefaults(matrix, axes = {}) {
	configureJavaDefaults(matrix, axes);
}

/**
 * @param {MatrixBuilder} matrix
 * @returns {{java_version: string}[]}
 */
function requireJvmMinMaxVersion(matrix) {
	let javaVersions = matrix.axisByName.java_version.values;
	return [
		{java_version: javaVersions[0]},
		{java_version: javaVersions[javaVersions.length - 1]},
	];
}

/**
 * @returns {{{os: string}[]}
 */
function requireUbuntuWindowsRows() {
	return [
		{os: 'ubuntu-latest'},
		{os: 'windows-latest'},
	];
}

/**
 * Generates JVM matrix rows and requires min/max Java version as well as ubuntu/windows.
 *
 * @param {MatrixBuilder} matrix - Matrix builder used to generate job rows.
 * @param {number} numberOfJobs - Default number of jobs to generate when MATRIX_JOBS environment variable is not set.
 * @param {Object[]} [additionalRequirements=[]] - Additional row requirements to apply when generating the matrix.
 * @returns {Object[]} Generated JVM matrix rows.
 * @throws {Error} If no matrix rows are generated.
 */
function generateJvmRows(matrix, numberOfJobs, additionalRequirements = []) {
	const include = matrix.generateRows(Number(process.env.MATRIX_JOBS || numberOfJobs), {
			require: [
				...requireJvmMinMaxVersion(matrix),
				...requireUbuntuWindowsRows(),
				...additionalRequirements
			]
		})
	;
	if (include.length === 0) {
		throw new Error('Matrix list is empty');
	}
	return include;
}

/**
 * @param {MatrixBuilder} matrix
 * @param {Object[]} include rows generated by the matrix.generateRows
 */
function setMatrix(matrix, include) {
	// Sort jobs by name, however, numeric parts are sorted appropriately.
	// For instance, 'windows 8' would come before 'windows 11'
	include.sort((a, b) => a.name.localeCompare(b.name, undefined, {numeric: true}));

	if (process.argv.includes('--coverage')) {
		const coverage = matrix.pairCoverageReport();
		console.log(`Pair coverage: ${coverage.covered}/${coverage.total} (${coverage.percentage}%), weighted ${coverage.weightPercentage}%`);
	} else {
		// Print the matrix to the job log for debugging.
		console.log(include);
		// Hand the matrix to the next job. setGitHubOutput writes $GITHUB_OUTPUT with a random,
		// multiline-safe delimiter, and no-ops when the variable is unset (e.g. running locally).
		setGitHubOutput('matrix', {include: include});
	}
}

/**
 * Creates a copy of an object with its values array filtered by a predicate.
 *
 * @template T
 * @template {Object} O
 * @param {O & {values: T[]}} obj - Object containing the values array to filter.
 * @param {(value: T, index: number, array: T[]) => boolean} predicate - Function used to test each value.
 * @returns {O & {values: T[]}} A copy of the original object with filtered values.
 */
function filterValues(obj, predicate) {
	return {...obj, values: obj.values.filter(predicate)};
}

export {
	javaDistributionAxis,
	javaVersionAxis,
	osAxis,
	setMatrix,
	configureJavaDefaults,
	configureKotlinDefaults,
	configureScalaDefaults,
	generateJvmRows,
	requireJvmMinMaxVersion,
	requireUbuntuWindowsRows,
	filterValues
};
